base:
  random_state: 42
  test_size: 0.2

data_ingestion:
  kaggle_dataset: "uciml/red-wine-quality-cortez-et-al-2009"

data_validation:
  validation_threshold: 0.05

data_transformation:
  numerical_features:
    - "fixed acidity"
    - "volatile acidity"
    - "citric acid"
    - "residual sugar"
    - "chlorides"
    - "free sulfur dioxide"
    - "total sulfur dioxide"
    - "density"
    - "pH"
    - "sulphates"
    - "alcohol"
  scaling_strategy: "StandardScaler"

model_trainer:
  models:
    ElasticNet:
      alpha: 0.1
      l1_ratio: 0.5
    RandomForest:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
    XGBoost:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6
      subsample: 0.8
      colsample_bytree: 0.8
  default_model: "RandomForest"

model_evaluation:
  metrics:
    - "rmse"
    - "mae"
    - "r2"